coverage:
  status:
    project:
      default:
        target: 60%
        threshold: 40%
comment:
  layout: "reach, diff, flags, files, header, footer"
  behavior: new
  require_changes: false
  require_head: no
  require_base: no