coverage:
  status:
    project:
      default:
        target: 50%
        threshold: 100%
        base: auto
    patch:
      default:
        target: 50%
        threshold: 100%
        base: auto
        if_ci_failed: error
        only_pulls: true
comment:
  layout: "reach, diff, flags, files, header, footer"
  behavior: new
  require_changes: false
  require_head: no
  require_base: no
