blank_issues_enabled: false
contact_links:
  - name: Class Tools Develop Team QQ Group
    url: https://jq.qq.com/?_wv=1027&k=PYH4ldDF
    about: Discuss with our team members here.
  - name: Class Tools Develop Team Official Website
    url: https://class-tools.github.io
    about: See introductions of our team here.