---

name: "Build"

on: [push, pull_request]

jobs:
  build-x86:
    name: Build x86
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Initialize vcpkg
        uses: johnwason/vcpkg-action@v4
        with:
          pkgs: jsoncpp spdlog
          triplet: x86-windows-static
          token: ${{ github.token }}
      - name: Build solution
        run: |
          .\vcpkg\vcpkg integrate install
          .\scripts\build.ps1 Release x86
  build-x64:
    name: Build x64
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Initialize vcpkg
        uses: johnwason/vcpkg-action@v4
        with:
          pkgs: jsoncpp spdlog
          triplet: x64-windows-static
          token: ${{ github.token }}
      - name: Build solution
        run: |
          .\vcpkg\vcpkg integrate install
          .\scripts\build.ps1 Release x64
  build-arm:
    name: Build ARM
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Initialize vcpkg
        uses: johnwason/vcpkg-action@v4
        with:
          pkgs: jsoncpp spdlog
          triplet: arm-windows-static
          token: ${{ github.token }}
      - name: Build solution
        run: |
          .\vcpkg\vcpkg integrate install
          .\scripts\build.ps1 Release ARM
  build-arm64:
    name: Build ARM64
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Initialize vcpkg
        uses: johnwason/vcpkg-action@v4
        with:
          pkgs: jsoncpp spdlog
          triplet: arm64-windows-static
          token: ${{ github.token }}
      - name: Build solution
        run: |
          .\vcpkg\vcpkg integrate install
          .\scripts\build.ps1 Release ARM64
