---

name: "Lint"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run Clang Format
        uses: DoozyX/clang-format-lint-action@v0.14
        with:
          extensions: 'cpp,hpp'
          exclude: '.\UnitTest\'
          clangFormatVersion: 14
          inplace: True
      - name: Commit Changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'SUM Adjust Source Code Format'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}