---

name: "Codecov"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  check:
    name: Check
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Initialize vcpkg
        run: |
          vcpkg integrate install
          vcpkg install jsoncpp:x64-windows jsoncpp:x64-windows-static
      - name: Setup MSBuild and add to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Run MSBuild
        run: msbuild .\UnitTest\UnitTest.vcxproj /p:Configuration=Release /p:Platform=x64
      - name: Setup VSTest and add to PATH
        uses: darenm/Setup-VSTest@v1
      - name: Setup OpenCppCoverage and add to PATH
        run: |
          choco install OpenCppCoverage -y
          echo "C:\Program Files\OpenCppCoverage" >> $env:GITHUB_PATH
      - name: Generate Report
        run: OpenCppCoverage.exe --verbose --sources WCH --export_type cobertura:WCH.xml -- "vstest.console.exe" .\x64\Release\UnitTest.dll
      - name: Upload Report to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: .\WCH.xml
          fail_ci_if_error: true