---

name: "Codecov"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  analyze:
    name: Analyze
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Initialize vcpkg
        uses: johnwason/vcpkg-action@v4
        with:
          triplet: 'x64-windows-static'
          cache-key: 'x64'
          token: ${{ github.token }}
          manifest-dir: '.'
      - name: Build solution
        run: |
          .\scripts\build.ps1 Release x64
      - name: Setup VSTest and add to PATH
        uses: darenm/Setup-VSTest@v1
      - name: Setup OpenCppCoverage and add to PATH
        run: |
          choco install OpenCppCoverage -y
          echo "C:\Program Files\OpenCppCoverage" >> $env:GITHUB_PATH
      - name: Generate report
        run: OpenCppCoverage --sources modules\apis.hpp --sources modules\basic.hpp --sources UnitTest\UnitTest.cpp --excluded_line_regex "\s*else.*" --excluded_line_regex "\s*\}.*" --export_type cobertura:WCH.xml -- "vstest.console.exe" x64\Release\UnitTest.dll
      - name: Upload report to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: .\WCH.xml
          fail_ci_if_error: true
