---

name: Check Commit Message

on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Check commit messages
        env:
          COMMIT_MSG: ${{ toJson(github.event.commits.*.message) }}
        run: |
          npm config set registry http://registry.npmjs.org/
          yarn config set registry https://registry.yarnpkg.com
          yarn add ct-git-commit-msg-std
          node ./node_modules/ct-git-commit-msg-std/check.js -c "$PWD/.gitmsgrc.cjs" -e COMMIT_MSG